# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userPw', models.CharField(max_length=30)),
            ],
        ),
    ]
